//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParallelWsTester.SoapFruitLoops {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isOKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfContentField;
        
        private long RunTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isOK {
            get {
                return this.isOKField;
            }
            set {
                if ((this.isOKField.Equals(value) != true)) {
                    this.isOKField = value;
                    this.RaisePropertyChanged("isOK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PdfContent {
            get {
                return this.PdfContentField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfContentField, value) != true)) {
                    this.PdfContentField = value;
                    this.RaisePropertyChanged("PdfContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long RunTime {
            get {
                return this.RunTimeField;
            }
            set {
                if ((this.RunTimeField.Equals(value) != true)) {
                    this.RunTimeField = value;
                    this.RaisePropertyChanged("RunTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapFruitLoops.FruitLoopsSoap")]
    public interface FruitLoopsSoap {
        
        // CODEGEN: Generating message contract since element name FileContent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertDOC", ReplyAction="*")]
        ParallelWsTester.SoapFruitLoops.ConvertDOCResponse ConvertDOC(ParallelWsTester.SoapFruitLoops.ConvertDOCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertDOC", ReplyAction="*")]
        System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertDOCResponse> ConvertDOCAsync(ParallelWsTester.SoapFruitLoops.ConvertDOCRequest request);
        
        // CODEGEN: Generating message contract since element name FileContent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertHTML", ReplyAction="*")]
        ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse ConvertHTML(ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertHTML", ReplyAction="*")]
        System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse> ConvertHTMLAsync(ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertDOCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertDOC", Namespace="http://tempuri.org/", Order=0)]
        public ParallelWsTester.SoapFruitLoops.ConvertDOCRequestBody Body;
        
        public ConvertDOCRequest() {
        }
        
        public ConvertDOCRequest(ParallelWsTester.SoapFruitLoops.ConvertDOCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertDOCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FileContent;
        
        public ConvertDOCRequestBody() {
        }
        
        public ConvertDOCRequestBody(string FileContent) {
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertDOCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertDOCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParallelWsTester.SoapFruitLoops.ConvertDOCResponseBody Body;
        
        public ConvertDOCResponse() {
        }
        
        public ConvertDOCResponse(ParallelWsTester.SoapFruitLoops.ConvertDOCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertDOCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ParallelWsTester.SoapFruitLoops.ResultDTO ConvertDOCResult;
        
        public ConvertDOCResponseBody() {
        }
        
        public ConvertDOCResponseBody(ParallelWsTester.SoapFruitLoops.ResultDTO ConvertDOCResult) {
            this.ConvertDOCResult = ConvertDOCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertHTMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertHTML", Namespace="http://tempuri.org/", Order=0)]
        public ParallelWsTester.SoapFruitLoops.ConvertHTMLRequestBody Body;
        
        public ConvertHTMLRequest() {
        }
        
        public ConvertHTMLRequest(ParallelWsTester.SoapFruitLoops.ConvertHTMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertHTMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FileContent;
        
        public ConvertHTMLRequestBody() {
        }
        
        public ConvertHTMLRequestBody(string FileContent) {
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertHTMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertHTMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParallelWsTester.SoapFruitLoops.ConvertHTMLResponseBody Body;
        
        public ConvertHTMLResponse() {
        }
        
        public ConvertHTMLResponse(ParallelWsTester.SoapFruitLoops.ConvertHTMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertHTMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ParallelWsTester.SoapFruitLoops.ResultDTO ConvertHTMLResult;
        
        public ConvertHTMLResponseBody() {
        }
        
        public ConvertHTMLResponseBody(ParallelWsTester.SoapFruitLoops.ResultDTO ConvertHTMLResult) {
            this.ConvertHTMLResult = ConvertHTMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FruitLoopsSoapChannel : ParallelWsTester.SoapFruitLoops.FruitLoopsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FruitLoopsSoapClient : System.ServiceModel.ClientBase<ParallelWsTester.SoapFruitLoops.FruitLoopsSoap>, ParallelWsTester.SoapFruitLoops.FruitLoopsSoap {
        
        public FruitLoopsSoapClient() {
        }
        
        public FruitLoopsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FruitLoopsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitLoopsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitLoopsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParallelWsTester.SoapFruitLoops.ConvertDOCResponse ParallelWsTester.SoapFruitLoops.FruitLoopsSoap.ConvertDOC(ParallelWsTester.SoapFruitLoops.ConvertDOCRequest request) {
            return base.Channel.ConvertDOC(request);
        }
        
        public ParallelWsTester.SoapFruitLoops.ResultDTO ConvertDOC(string FileContent) {
            ParallelWsTester.SoapFruitLoops.ConvertDOCRequest inValue = new ParallelWsTester.SoapFruitLoops.ConvertDOCRequest();
            inValue.Body = new ParallelWsTester.SoapFruitLoops.ConvertDOCRequestBody();
            inValue.Body.FileContent = FileContent;
            ParallelWsTester.SoapFruitLoops.ConvertDOCResponse retVal = ((ParallelWsTester.SoapFruitLoops.FruitLoopsSoap)(this)).ConvertDOC(inValue);
            return retVal.Body.ConvertDOCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertDOCResponse> ParallelWsTester.SoapFruitLoops.FruitLoopsSoap.ConvertDOCAsync(ParallelWsTester.SoapFruitLoops.ConvertDOCRequest request) {
            return base.Channel.ConvertDOCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertDOCResponse> ConvertDOCAsync(string FileContent) {
            ParallelWsTester.SoapFruitLoops.ConvertDOCRequest inValue = new ParallelWsTester.SoapFruitLoops.ConvertDOCRequest();
            inValue.Body = new ParallelWsTester.SoapFruitLoops.ConvertDOCRequestBody();
            inValue.Body.FileContent = FileContent;
            return ((ParallelWsTester.SoapFruitLoops.FruitLoopsSoap)(this)).ConvertDOCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse ParallelWsTester.SoapFruitLoops.FruitLoopsSoap.ConvertHTML(ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest request) {
            return base.Channel.ConvertHTML(request);
        }
        
        public ParallelWsTester.SoapFruitLoops.ResultDTO ConvertHTML(string FileContent) {
            ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest inValue = new ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest();
            inValue.Body = new ParallelWsTester.SoapFruitLoops.ConvertHTMLRequestBody();
            inValue.Body.FileContent = FileContent;
            ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse retVal = ((ParallelWsTester.SoapFruitLoops.FruitLoopsSoap)(this)).ConvertHTML(inValue);
            return retVal.Body.ConvertHTMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse> ParallelWsTester.SoapFruitLoops.FruitLoopsSoap.ConvertHTMLAsync(ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest request) {
            return base.Channel.ConvertHTMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParallelWsTester.SoapFruitLoops.ConvertHTMLResponse> ConvertHTMLAsync(string FileContent) {
            ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest inValue = new ParallelWsTester.SoapFruitLoops.ConvertHTMLRequest();
            inValue.Body = new ParallelWsTester.SoapFruitLoops.ConvertHTMLRequestBody();
            inValue.Body.FileContent = FileContent;
            return ((ParallelWsTester.SoapFruitLoops.FruitLoopsSoap)(this)).ConvertHTMLAsync(inValue);
        }
    }
}
